/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7Fl7mHsyRYy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"
import { Checkbox } from "@/components/ui/checkbox"
import { Slider } from "@/components/ui/slider"
import { Progress } from "@/components/ui/progress"

export function box() {
  return (
    <div className="container mx-auto py-8 px-4 md:px-6">
      <div className="max-w-2xl mx-auto">
        <div className="mb-6">
          <h1 className="text-3xl font-bold mb-2">Habit Tracker</h1>
          <p className="text-gray-500 dark:text-gray-400">Stay on top of your daily routines.</p>
        </div>
        <div className="bg-white dark:bg-gray-950 rounded-lg shadow-md p-6 mb-6">
          <div className="flex items-center mb-4">
            <input
              className="flex-1 bg-gray-100 dark:bg-gray-800 border-none rounded-md py-2 px-4 focus:ring-2 focus:ring-gray-900 focus:outline-none dark:focus:ring-gray-50"
              placeholder="Add a new habit"
              type="text"
            />
            <Button className="ml-4">Add</Button>
          </div>
          <Accordion collapsible type="single">
            <AccordionItem value="exercise">
              <AccordionTrigger className="text-lg font-medium">Exercise</AccordionTrigger>
              <AccordionContent>
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <Checkbox defaultChecked id="exercise-1" />
                      <div>
                        <p className="font-medium">Morning Jog</p>
                        <p className="text-gray-500 dark:text-gray-400 text-sm">Today, 7:00 AM</p>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <p className="font-medium">High</p>
                      <Slider className="w-24" defaultValue={[80]} id="exercise-1-priority" max={100} step={10} />
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <Checkbox id="exercise-2" />
                      <div>
                        <p className="font-medium">Strength Training</p>
                        <p className="text-gray-500 dark:text-gray-400 text-sm">Today, 6:00 PM</p>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <p className="font-medium">Medium</p>
                      <Slider className="w-24" defaultValue={[60]} id="exercise-2-priority" max={100} step={10} />
                    </div>
                  </div>
                </div>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="personal">
              <AccordionTrigger className="text-lg font-medium">Personal</AccordionTrigger>
              <AccordionContent>
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <Checkbox defaultChecked id="personal-1" />
                      <div>
                        <p className="font-medium">Meditate</p>
                        <p className="text-gray-500 dark:text-gray-400 text-sm">Today, 8:00 AM</p>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <p className="font-medium">High</p>
                      <Slider className="w-24" defaultValue={[90]} id="personal-1-priority" max={100} step={10} />
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <Checkbox id="personal-2" />
                      <div>
                        <p className="font-medium">Journal</p>
                        <p className="text-gray-500 dark:text-gray-400 text-sm">Today, 9:00 PM</p>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <p className="font-medium">Medium</p>
                      <Slider className="w-24" defaultValue={[70]} id="personal-2-priority" max={100} step={10} />
                    </div>
                  </div>
                </div>
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>
        <div className="bg-white dark:bg-gray-950 rounded-lg shadow-md p-6">
          <h2 className="text-2xl font-bold mb-4">Progress</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
              <p className="font-medium mb-2">Morning Jog</p>
              <div className="flex items-center justify-between">
                <p className="text-gray-500 dark:text-gray-400 text-sm">7 days this month</p>
                <p className="font-medium">70%</p>
              </div>
              <Progress className="mt-2" value={70} />
            </div>
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
              <p className="font-medium mb-2">Strength Training</p>
              <div className="flex items-center justify-between">
                <p className="text-gray-500 dark:text-gray-400 text-sm">4 days this month</p>
                <p className="font-medium">40%</p>
              </div>
              <Progress className="mt-2" value={40} />
            </div>
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
              <p className="font-medium mb-2">Meditate</p>
              <div className="flex items-center justify-between">
                <p className="text-gray-500 dark:text-gray-400 text-sm">25 days this month</p>
                <p className="font-medium">90%</p>
              </div>
              <Progress className="mt-2" value={90} />
            </div>
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
              <p className="font-medium mb-2">Journal</p>
              <div className="flex items-center justify-between">
                <p className="text-gray-500 dark:text-gray-400 text-sm">18 days this month</p>
                <p className="font-medium">60%</p>
              </div>
              <Progress className="mt-2" value={60} />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
